[input]
type = "LogstreamerInput"
log_directory = "/var/lib/docker/containers"
file_match = '(?P<Container>[^/]+)/[a-zA-Z0-9]+-json.log?(?P<Index>\d+)?(.gz)?'
priority = ["^Index"]
differentiator = ["Container"]
 
 
[logentriesEncoder]
type = "SandboxEncoder"
filename = "/usr/share/heka/lua_encoders/logentries.lua"
 
        [logentriesEncoder.config]
        token = "%TOKEN%"
 
[logentriesOutput]
type = "TcpOutput"
address = "api.logentries.com:20000"
encoder = "logentriesEncoder"
message_matcher = "Type == 'logfile'"
use_tls = true

    [logentriesOutput.tls]
    server_name = "api.logentries.com"
