[input]
type = "DockerLogInput"
 
[logentriesEncoder]
type = "SandboxEncoder"
filename = "/usr/share/heka/lua_encoders/logentries.lua"
 
        [logentriesEncoder.config]
        token = "%TOKEN%"
 
[logentriesOutput]
type = "TcpOutput"
address = "api.logentries.com:20000"
encoder = "logentriesEncoder"
message_matcher = "Type == 'DockerLog'"
use_tls = true

    [logentriesOutput.tls]
    server_name = "api.logentries.com"